config/routes.rb
Rails.application.routes.draw do

  resources :listings
  resources :communities
  resources :share_categories
  resources :share_types
  resources :listing_categories
  resources :listing_types
  resources :users

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :listing_type
  belongs_to :listing_category
  belongs_to :user
  belongs_to :community
  belongs_to :share_type
  belongs_to :share_category

  def pretty_title
    title.split(' ').map { |x| x.capitalize }.join(' ')
  end
end

app/models/listing_type.rb
class ListingType < ActiveRecord::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    #@listings = Listing.all
    @offerings = Listing.all.where(listing_type_id: 1)
    @wanted    = Listing.all.where(listing_type_id: 2)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :user_id, :community_id, :listing_type_id, :listing_category_id, :share_type_id, :share_category_id, :txn_terms, :description)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing, html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :title, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= f.text_field :title %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :user_id, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= collection_select(:listing, :user_id, User.all, :id, :name, {include_blank: false}, class: 'form-control') %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :community_id, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= collection_select(:listing, :community_id, Community.all, :id, :name, {include_blank: false}) %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :listing_type_id, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= collection_select(:listing, :listing_type_id, ListingType.all, :id, :name, {include_blank: false}) %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :listing_category_id, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= collection_select(:listing, :listing_category_id, ListingCategory.all, :id, :name, {include_blank: false}) %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :share_type_id, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= collection_select(:listing, :share_type_id, ShareType.all, :id, :name, {include_blank: false}) %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :share_category_id, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= collection_select(:listing, :share_category_id, ShareCategory.all, :id, :name, {include_blank: false}) %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :txn_terms, class: 'col-lg-2 control-label' %>
    <div class='col-lg-4'>
        <%= f.text_field :txn_terms %>
    </div>
  </div>

  <div class='form-group col-lg-4'>
    <%= f.label :description, class: 'col-lg-3 control-label' %>
    <div class='col-lg-4'>
        <%= f.text_area :description %>
    </div>
  </div>

    <div class="form-group">
      <div class="col-lg-offset-1 col-lg-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
<% end %>

app/views/listings/_listings.html.erb
<div id='offerings' class='active'>
  <table class='table table-striped'>
    <tbody>
    <% @offerings.each do |listing| %>
        <tr>
          <td><%= listing.listing_category.name %></td>
          <td><%= link_to listing.title, listing %></td>
          <td><%= listing.listing_type.name %></td>
          <td><%= listing.user_id %></td>
          <td><%= listing.community.name %></td>

          <!--
                <td><%#= link_to 'Show', listing %></td>
                <td><%#= link_to 'Edit', edit_listing_path(listing) %></td>
                <td><%#= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                -->
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/listings/_wanted.html.erb
<div id='wanted'>
  <table class='table table-striped'>
    <tbody>
    <% @wanted.each do |listing| %>
        <tr>
          <td><%= listing.listing_category.name %></td>
          <td><%= link_to listing.title, listing %></td>
          <td><%= listing.listing_type.name %></td>
          <td><%= listing.user_id %></td>
          <td><%= listing.community.name %></td>

          <!--
                <td><%#= link_to 'Show', listing %></td>
                <td><%#= link_to 'Edit', edit_listing_path(listing) %></td>
                <td><%#= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                -->
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listings</h1>


<ul class="nav nav-tabs" role="tablist">
  <li id='offerings_tab' class="active"><a class='nav_tab'>Offerings</a></li>
  <li id='wanted_tab'><a class='nav_tab'>Wanted</a></li>
</ul>


<div id='listings'>
    <%= render 'listings/listings' %>

    <%= render 'listings/wanted' %>
</div>

<br>

<%= link_to 'New Listing', new_listing_path %>



<script type='text/javascript'>
    $(document).ready(function(){
        new app.Listings.CreateViewController();
    });
</script>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Edit', edit_listing_path(@listing) %> |
  <%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.pretty_title %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user.name %>
</p>

<p>
  <strong>Community:</strong>
  <%= @listing.community.name %>
</p>

<p>
  <strong>Listing type:</strong>
  <%= @listing.listing_type.name %>
</p>

<p>
  <strong>Listing category:</strong>
  <%= @listing.listing_category.name %>
</p>

<p>
  <strong>Share type:</strong>
  <%= @listing.share_type.name %>
</p>

<p>
  <strong>Share category:</strong>
  <%= @listing.share_category.name %>
</p>

<p>
  <strong>Txn terms:</strong>
  <%= @listing.txn_terms %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>


<%= link_to 'Back', listings_path %>