config/routes.rb
Rails.application.routes.draw do

  resources :listings
  resources :communities
  resources :share_categories
  resources :share_types
  resources :listing_categories
  resources :listing_types
  resources :users

  root 'listings#index'

end

app/controllers/listing_types_controller.rb
class ListingTypesController < ApplicationController
  before_action :set_listing_type, only: [:show, :edit, :update, :destroy]

  # GET /listing_types
  # GET /listing_types.json
  def index
    @listing_types = ListingType.all
  end

  # GET /listing_types/1
  # GET /listing_types/1.json
  def show
  end

  # GET /listing_types/new
  def new
    @listing_type = ListingType.new
  end

  # GET /listing_types/1/edit
  def edit
  end

  # POST /listing_types
  # POST /listing_types.json
  def create
    @listing_type = ListingType.new(listing_type_params)

    respond_to do |format|
      if @listing_type.save
        format.html { redirect_to @listing_type, notice: 'Listing type was successfully created.' }
        format.json { render :show, status: :created, location: @listing_type }
      else
        format.html { render :new }
        format.json { render json: @listing_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listing_types/1
  # PATCH/PUT /listing_types/1.json
  def update
    respond_to do |format|
      if @listing_type.update(listing_type_params)
        format.html { redirect_to @listing_type, notice: 'Listing type was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing_type }
      else
        format.html { render :edit }
        format.json { render json: @listing_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listing_types/1
  # DELETE /listing_types/1.json
  def destroy
    @listing_type.destroy
    respond_to do |format|
      format.html { redirect_to listing_types_url, notice: 'Listing type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing_type
      @listing_type = ListingType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_type_params
      params.require(:listing_type).permit(:name)
    end
end

app/helpers/listing_types_helper.rb
module ListingTypesHelper
end

app/views/listing_types/_form.html.erb
<%= form_for(@listing_type) do |f| %>
  <% if @listing_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing_type.errors.count, "error") %> prohibited this listing_type from being saved:</h2>

      <ul>
      <% @listing_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listing_types/edit.html.erb
<h1>Editing listing_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing_type %> |
<%= link_to 'Back', listing_types_path %>

app/views/listing_types/index.html.erb
<h1>Listing Types</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listing_types.each do |listing_type| %>
      <tr>
        <td><%= listing_type.name %></td>
        <td><%= link_to 'Show', listing_type %></td>
        <td><%= link_to 'Edit', edit_listing_type_path(listing_type) %></td>
        <td><%= link_to 'Destroy', listing_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing type', new_listing_type_path %>

app/views/listing_types/new.html.erb
<h1>New listing_type</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_types_path %>

app/views/listing_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing_type.name %>
</p>

<%= link_to 'Edit', edit_listing_type_path(@listing_type) %> |
<%= link_to 'Back', listing_types_path %>