config/routes.rb
Rails.application.routes.draw do

  resources :listings
  resources :communities
  resources :share_categories
  resources :share_types
  resources :listing_categories
  resources :listing_types
  resources :users

  root 'listings#index'

end

app/controllers/share_types_controller.rb
class ShareTypesController < ApplicationController
  before_action :set_share_type, only: [:show, :edit, :update, :destroy]

  # GET /share_types
  # GET /share_types.json
  def index
    @share_types = ShareType.all
  end

  # GET /share_types/1
  # GET /share_types/1.json
  def show
  end

  # GET /share_types/new
  def new
    @share_type = ShareType.new
  end

  # GET /share_types/1/edit
  def edit
  end

  # POST /share_types
  # POST /share_types.json
  def create
    @share_type = ShareType.new(share_type_params)

    respond_to do |format|
      if @share_type.save
        format.html { redirect_to @share_type, notice: 'Share type was successfully created.' }
        format.json { render :show, status: :created, location: @share_type }
      else
        format.html { render :new }
        format.json { render json: @share_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /share_types/1
  # PATCH/PUT /share_types/1.json
  def update
    respond_to do |format|
      if @share_type.update(share_type_params)
        format.html { redirect_to @share_type, notice: 'Share type was successfully updated.' }
        format.json { render :show, status: :ok, location: @share_type }
      else
        format.html { render :edit }
        format.json { render json: @share_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /share_types/1
  # DELETE /share_types/1.json
  def destroy
    @share_type.destroy
    respond_to do |format|
      format.html { redirect_to share_types_url, notice: 'Share type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share_type
      @share_type = ShareType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_type_params
      params.require(:share_type).permit(:name)
    end
end

app/helpers/share_types_helper.rb
module ShareTypesHelper
end

app/views/share_types/_form.html.erb
<%= form_for(@share_type) do |f| %>
  <% if @share_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share_type.errors.count, "error") %> prohibited this share_type from being saved:</h2>

      <ul>
      <% @share_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/share_types/edit.html.erb
<h1>Editing share_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @share_type %> |
<%= link_to 'Back', share_types_path %>

app/views/share_types/index.html.erb
<h1>Share Types</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @share_types.each do |share_type| %>
      <tr>
        <td><%= share_type.name %></td>
        <td><%= link_to 'Show', share_type %></td>
        <td><%= link_to 'Edit', edit_share_type_path(share_type) %></td>
        <td><%= link_to 'Destroy', share_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Share type', new_share_type_path %>

app/views/share_types/new.html.erb
<h1>New share_type</h1>

<%= render 'form' %>

<%= link_to 'Back', share_types_path %>

app/views/share_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @share_type.name %>
</p>

<%= link_to 'Edit', edit_share_type_path(@share_type) %> |
<%= link_to 'Back', share_types_path %>